# Generated by Django 2.2.24 on 2024-05-11 11:10

from django.db import migrations

from property.models import Flat


def auto_flat_construction_year(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(auto_flat_construction_year)
    ]


