# Generated by Django 2.2.24 on 2024-05-11 11:10

from django.db import migrations

from property.models import Flat


def auto_flat_construction_year(apps, schema_editor):
    for flat in Flat.objects.all():
        if flat.construction_year >= 2015:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(auto_flat_construction_year)
    ]


