# Generated by Django 2.2.24 on 2024-05-14 20:08
import phonenumbers
from django.db import migrations
from property.models import Flat


def normalization_phonenumbers(apps, schema_editor):
    FlatModel = apps.get_model('property', 'Flat')
    for flat in FlatModel.objects.iterator():
        phone_number = flat.owners_phonenumber
        parsed_number = phonenumbers.parse(phone_number, "RU")
        if phonenumbers.is_valid_number(parsed_number):
            flat.owner_pure_phone = phonenumbers.format_number(parsed_number, phonenumbers.PhoneNumberFormat.E164)
        else:
            flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalization_phonenumbers),
    ]
